import turtle
screen=turtle.Screen()
screen.title("almanya bayrağı")
screen.bgcolor("gray")

bayrak=turtle.Turtle()
bayrak.pensize(5)
bayrak.width(2)
bayrak.speed(6)
def bayrakcizimi():
    bayrak.penup()
    bayrak.goto(-100,0)
    bayrak.pendown()
    bayrak.color("black")
    bayrak.begin_fill()
    for i in range(2):
        bayrak.forward(400)
        bayrak.left(90)
        bayrak.forward(300)
        bayrak.left(90)
    bayrak.end_fill()
bayrakcizimi()
bayrak.penup()
bayrak.goto(-100,100)
bayrak.pendown()
bayrak.color("red")
bayrak.begin_fill()
for _ in range(2):
    bayrak.forward(400)
    bayrak.left(90)
    bayrak.forward(100)
    bayrak.left(90)
bayrak.end_fill()

bayrak.penup()
bayrak.goto(-100,0)
bayrak.pendown()
bayrak.color("yellow")
bayrak.begin_fill()
for _ in range(2):
    bayrak.forward(400)
    bayrak.left(90)
    bayrak.forward(100)
    bayrak.left(90)
bayrak.end_fill()
screen.mainloop()