import turtle
wn = turtle.Screen()
wn.title("Ninja Turtles")

michelangelo = turtle.Turtle()
michelangelo.color("orange")
michelangelo.pensize(5)
michelangelo.shape('turtle')
michelangelo.speed(1)
michelangelo.begin_fill()
for i in range(4):
    michelangelo.forward(240)
    michelangelo.left(90)
michelangelo.right(180)
michelangelo.forward(180)
michelangelo.end_fill()

leonardo = turtle.Turtle()
leonardo.pensize(5)
leonardo.color("blue")
leonardo.shape('turtle')
leonardo.speed(6)
leonardo.begin_fill()
for i in range(4):
    leonardo.forward(180)
    leonardo.left(90)
leonardo.right(180)
leonardo.forward(140)
leonardo.end_fill()

donatello = turtle.Turtle()
donatello.color("purple")
donatello.pensize(5)
donatello.shape('turtle')
donatello.speed(6)
donatello.begin_fill()
for i in range(4):
    donatello.forward(120)
    donatello.left(90)
donatello.right(180)
donatello.forward(100)
donatello.end_fill()

raphael = turtle.Turtle()
raphael.color("red")
raphael.pensize(5)
raphael.shape('turtle')
raphael.speed(6)
raphael.begin_fill()
for i in range(4):
    raphael.forward(60)
    raphael.left(90)
raphael.right(180)
raphael.forward(60)
raphael.end_fill()
turtle.done()